name: SAST .NET

on:
  workflow_dispatch:    

jobs:
  build:

    # runs-on: self-hosted
    runs-on: ubuntu-latest
    # runs-on: windows-2019
    # runs-on: windows-2022

    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4
      with:
        repository: gable-tdd-nconnect/nconnect-solution
        ref: develop
        token: ${{ secrets.WORKFLOW_TOKEN }}

    - name: Checkout Current Repo
      uses: actions/checkout@v4
      with:
        path: my_repo

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: csharp

    - name: Autobuild
      uses: github/codeql-action/autobuild@v3

    - name: Perform CodeQL Analysis
      continue-on-error: true
      uses: github/codeql-action/analyze@v3

    - name: Verify Result
      run: |
        pwd
        ls -lrt
        ls -lrt ../results/csharp.sarif

    - name: Update Sarif Result
      run: |
        pwd
        cp ../results/csharp.sarif my_repo
        cd my_repo
        ls -lrt
        git config user.name "GitHub Actions Bot"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update SARIF security results"
        git push
   
          
